name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Install cask app
        run: brew install --cask react-native-debugger

      - name: tap createzap
        run: brew tap nrlquaker/createzap

      - name: Open app
        run: osascript -e "tell application \"React Native Debugger\" to activate"

      - name: createzap
        run: brew createzap react-native-debugger