name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Install cask app
        run: brew install --cask poedit

      - name: tap createzap
        run: brew tap nrlquaker/createzap

      - name: Open app
        working-directory: /Application/
        run: open -a poedit

      - name: createzap
        run: brew createzap poedit

