name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Install cask app
        run: brew install --cask poedit

      - name: tap createzap
        run: brew tap nrlquaker/createzap

      - name: Docker
        run: |
          docker run -it \
              --device /dev/kvm \
              -p 50922:10022 \
              -v /tmp/.X11-unix:/tmp/.X11-unix \
              -e "DISPLAY=${DISPLAY:-:0.0}" \
              sickcodes/docker-osx:big-sur

      - name: createzap
        run: brew createzap poedit

